CREATE TABLE IF NOT EXISTS CURSO (
    CUR_INT_ID BIGSERIAL PRIMARY KEY,
    CUR_STR_NOME VARCHAR(100) NOT NULL,
    CUR_STR_SIGLA VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROFESSOR (
    PRO_INT_ID BIGSERIAL PRIMARY KEY,
    PRO_STR_NOME VARCHAR(100) NOT NULL,
    PRO_STR_EMAIL VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS USUARIO (
    USU_INT_ID BIGSERIAL PRIMARY KEY,
    USU_STR_NOME VARCHAR(100) NOT NULL,
    USU_STR_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    USU_STR_SENHA VARCHAR(255) NOT NULL,
    USU_STR_CARGO VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS SEMESTRE (
    SEM_INT_ID BIGSERIAL PRIMARY KEY,
    CUR_INT_ID BIGINT NOT NULL REFERENCES CURSO(CUR_INT_ID),
    SEM_INT_ORDEM INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS MATERIA (
    MAT_INT_ID BIGSERIAL PRIMARY KEY,
    SEM_INT_ID BIGINT NOT NULL REFERENCES SEMESTRE(SEM_INT_ID),
    MAT_STR_NOME VARCHAR(100) NOT NULL,
    MAT_STR_SIGLA VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROFESSOR_MATERIA (
    PMA_INT_ID BIGSERIAL PRIMARY KEY,
    PRO_INT_ID BIGINT NOT NULL REFERENCES PROFESSOR(PRO_INT_ID),
    MAT_INT_ID BIGINT NOT NULL REFERENCES MATERIA(MAT_INT_ID),
    PMA_STR_TURNO VARCHAR(10),
    MET_JSON_FORMULA TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_SEMESTRE_CURSO ON SEMESTRE(CUR_INT_ID);
CREATE INDEX IF NOT EXISTS IDX_MATERIA_SEMESTRE ON MATERIA(SEM_INT_ID);
CREATE INDEX IF NOT EXISTS IDX_PROFESSOR_MATERIA_PROFESSOR ON PROFESSOR_MATERIA(PRO_INT_ID);
CREATE INDEX IF NOT EXISTS IDX_PROFESSOR_MATERIA_MATERIA ON PROFESSOR_MATERIA(MAT_INT_ID);
